// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-customers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_customers_default = defineTool({
  name: "list_customers",
  title: "List customers",
  description: "List customers in the accounting system. Optional search filter matches name, code, or phone.",
  inputSchema: {
    search: z.string().optional().describe("Optional search term (name/code/phone)."),
    limit: z.number().int().min(1).max(200).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("customers").select("id, code, name, phone, email, balance, is_active").order("name", { ascending: true }).limit(limit);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      query = query.or(`name.ilike.${s},code.ilike.${s},phone.ilike.${s}`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_suppliers_default = defineTool2({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List suppliers. Optional search matches name, code, or phone.",
  inputSchema: {
    search: z2.string().optional(),
    limit: z2.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("suppliers").select("id, code, name, phone, email, balance, is_active").order("name", { ascending: true }).limit(limit);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      query = query.or(`name.ilike.${s},code.ilike.${s},phone.ilike.${s}`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_products_default = defineTool3({
  name: "list_products",
  title: "List products",
  description: "List products with stock and price. Optional search matches name, code, brand, or model.",
  inputSchema: {
    search: z3.string().optional(),
    only_active: z3.boolean().default(true),
    limit: z3.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser3(ctx);
    let query = supabase.from("products").select(
      "id, code, name, brand, model, selling_price, average_cost, available_quantity, is_active"
    ).order("name", { ascending: true }).limit(limit);
    if (only_active) query = query.eq("is_active", true);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      query = query.or(
        `name.ilike.${s},code.ilike.${s},brand.ilike.${s},model.ilike.${s}`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-sales-invoices.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_sales_invoices_default = defineTool4({
  name: "list_sales_invoices",
  title: "List sales invoices",
  description: "List recent sales invoices with totals and status. Filter by date range and/or status.",
  inputSchema: {
    from_date: z4.string().optional().describe("YYYY-MM-DD lower bound (inclusive)."),
    to_date: z4.string().optional().describe("YYYY-MM-DD upper bound (inclusive)."),
    status: z4.enum(["draft", "posted", "cancelled"]).optional(),
    limit: z4.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser4(ctx);
    let query = supabase.from("sales_invoices").select(
      "id, posted_number, invoice_date, customer_id, total, net_total, paid_amount, status"
    ).order("invoice_date", { ascending: false }).limit(limit);
    if (from_date) query = query.gte("invoice_date", from_date);
    if (to_date) query = query.lte("invoice_date", to_date);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { invoices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-sales-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_sales_summary_default = defineTool5({
  name: "get_sales_summary",
  title: "Sales summary for a period",
  description: "Aggregate posted sales invoices over a date range (count, gross total, net total, paid, outstanding).",
  inputSchema: {
    from_date: z5.string().describe("YYYY-MM-DD lower bound (inclusive)."),
    to_date: z5.string().describe("YYYY-MM-DD upper bound (inclusive).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser5(ctx);
    const { data, error } = await supabase.from("sales_invoices").select("total, net_total, paid_amount, status").eq("status", "posted").gte("invoice_date", from_date).lte("invoice_date", to_date);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const summary = rows.reduce(
      (acc, r) => {
        acc.count += 1;
        acc.total += Number(r.total ?? 0);
        acc.net_total += Number(r.net_total ?? 0);
        acc.paid += Number(r.paid_amount ?? 0);
        return acc;
      },
      { count: 0, total: 0, net_total: 0, paid: 0 }
    );
    const outstanding = summary.net_total - summary.paid;
    const result = { from_date, to_date, ...summary, outstanding };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ejfoidwbeygzzkbonbmq";
var mcp_default = defineMcp({
  name: "accounting-system-mcp",
  title: "\u0627\u0644\u0646\u0638\u0627\u0645 \u0627\u0644\u0645\u062D\u0627\u0633\u0628\u064A \u2014 MCP",
  version: "0.1.0",
  instructions: "Read-only tools for this accounting system: list customers, suppliers, products, sales invoices, and get a sales summary for a date range. All queries respect the signed-in user's permissions (RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_customers_default,
    list_suppliers_default,
    list_products_default,
    list_sales_invoices_default,
    get_sales_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
